// <auto-generated />
using System;
using JWTAuthentication.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JWTAuthentication.Persistence.Migrations.Postgres
{
    [DbContext(typeof(AuthenticationOrganizationContextPostgreSQL))]
    [Migration("20241024211622_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("app")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JWTAuthentication.Domain.Usuarios.JwsClaims.JwtClaim", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Removed")
                        .HasColumnType("boolean");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Uuid");

                    b.ToTable("JwtClaim", "app");
                });

            modelBuilder.Entity("JWTAuthentication.Domain.Usuarios.Roles.Role", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Removed")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Uuid");

                    b.ToTable("Role", "app");
                });

            modelBuilder.Entity("JWTAuthentication.Domain.Usuarios.Roles.RoleJwtClaims.RoleJwtClaim", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("JwtClaimUuid")
                        .HasColumnType("uuid");

                    b.Property<bool>("Removed")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("RoleUuid")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Uuid");

                    b.HasIndex("JwtClaimUuid");

                    b.HasIndex("RoleUuid");

                    b.ToTable("RoleJwtClaim", "app");
                });

            modelBuilder.Entity("JWTAuthentication.Domain.Usuarios.Usuario", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("JwtClaimUuid")
                        .HasColumnType("uuid");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Removed")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdateAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Uuid");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("JwtClaimUuid");

                    b.ToTable("Usuario", "app");
                });

            modelBuilder.Entity("JWTAuthentication.Domain.Usuarios.Roles.RoleJwtClaims.RoleJwtClaim", b =>
                {
                    b.HasOne("JWTAuthentication.Domain.Usuarios.JwsClaims.JwtClaim", "JwtClaim")
                        .WithMany("RoleJwtClaims")
                        .HasForeignKey("JwtClaimUuid");

                    b.HasOne("JWTAuthentication.Domain.Usuarios.Roles.Role", "Role")
                        .WithMany("RoleJwtClaims")
                        .HasForeignKey("RoleUuid");

                    b.Navigation("JwtClaim");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("JWTAuthentication.Domain.Usuarios.Usuario", b =>
                {
                    b.HasOne("JWTAuthentication.Domain.Usuarios.JwsClaims.JwtClaim", "JwtClaims")
                        .WithMany()
                        .HasForeignKey("JwtClaimUuid");

                    b.Navigation("JwtClaims");
                });

            modelBuilder.Entity("JWTAuthentication.Domain.Usuarios.JwsClaims.JwtClaim", b =>
                {
                    b.Navigation("RoleJwtClaims");
                });

            modelBuilder.Entity("JWTAuthentication.Domain.Usuarios.Roles.Role", b =>
                {
                    b.Navigation("RoleJwtClaims");
                });
#pragma warning restore 612, 618
        }
    }
}
