version: "3.8"

services:
  postgres-sql:
    image: postgres:17.0-alpine3.20
    restart: always
    environment:
      POSTGRES_USER: userdb1
      POSTGRES_PASSWORD: senhadb1
      POSTGRES_DB: postgres-sql
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data1:/var/lib/postgresql/data
  api-cqrs:
    build:
      context: ./api/JWTAuthentication
      dockerfile: Dockerfile.APICQRS
    ports:
      - "5004:5000"
    depends_on:
      - postgres-sql
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5000
      - ASPNETCORE_Kestrel__Certificates__Default__Password=mypassword123
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/certificate.pfx
    volumes:
      - ./api/JWTAuthentication/certificate.pfx:/https/certificate.pfx:ro
    restart: always
    networks:
      - elastic
networks:
  elastic:
    driver: bridge
volumes:
  postgres-data1:
    driver: local
