version: "3.8"

services:
  sql-server:
    build:
      context: ./data-base
    ports:
      - "1433:1433"
    networks:
      - elastic
  mssqltools:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      - sql-server
    volumes:
      - ./data-base/init-database.sh:/tmp/init-database.sh
      - ./data-base/sql-scripts/init-authentication-db.sql:/tmp/init-authentication-db.sql
    command: /bin/bash ./tmp/init-database.sh
    networks:
      - elastic
  api:
    build:
      context: ./api/JWTAuthentication
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    depends_on:
      - mssqltools
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=https://+:5002;http://+:5000
      - ASPNETCORE_Kestrel__Certificates__Default__Password=mypassword123
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ./certificate.pfx:/https/certificate.pfx:ro
    restart: always
    networks:
      - elastic
networks:
  elastic:
    driver: bridge
