version: "3.8"

services:
  sql-server:
    build:
      context: ./data-base-sql-server
    ports:
      - "1431:1433"
    networks:
      - elastic
  mssqltools:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      - sql-server
    volumes:
      - ./data-base-sql-server/init-database.sh:/tmp/init-database.sh
      - ./data-base-sql-server/sql-scripts/init-authentication-db.sql:/tmp/init-authentication-db.sql
    command: /bin/bash ./tmp/init-database.sh
    networks:
      - elastic
  api:
    build:
      context: ./api/JWTAuthentication
      dockerfile: Dockerfile.API
    ports:
      - "5002:5000"
    depends_on:
      - mssqltools
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5000
      - ASPNETCORE_Kestrel__Certificates__Default__Password=mypassword123
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/certificate.pfx
    volumes:
      - ./api/JWTAuthentication/certificate.pfx:/https/certificate.pfx:ro
    restart: always
    networks:
      - elastic
networks:
  elastic:
    driver: bridge
